/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tracker;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        Tracker tracker = new Tracker();
        tracker.startTracker(scanner);

        scanner.close();
    }
}
